os: linux
dist: trusty
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_REPO='ojkwon/arch-emscripten'
    - EMSCRIPTEN_VERSION=1.38.13-1
    - PROTOBUF_VERSION=3.5.2
  matrix:
    - BUILD_TARGET='base'
    - BUILD_TARGET='protobuf'

matrix:
  # let whole build fails if one of matrix build config fails
  fast_finish: true

script:
  - COMMIT=${TRAVIS_COMMIT::8}
  # set docker tag based on last commit short sha.
  - DOCKER_TAG=$DOCKER_REPO:${COMMIT}-$BUILD_TARGET
  - tput setaf 2; echo building docker image tagged as $DOCKER_TAG
  - sudo docker build --tag $DOCKER_TAG --build-arg BUILD_TARGET=$BUILD_TARGET --build-arg PROTOBUF_VERSION=$PROTOBUF_VERSION --build-arg EMSCRIPTEN_VERSION=$EMSCRIPTEN_VERSION .
  - |
    if [[ ! -z "${TRAVIS_TAG}" ]]; then
      tput setaf 2; echo this build is tagged versioned build, pushing into registry
      sudo docker login -u=ojkwon -p="$DOCKER_PASSWORD"
      sudo docker push $DOCKER_TAG
    fi